# Matched from /home/yssu/dotfiles/sys/.Xresources URxvt settings.

[main]
font=Source Code Pro Medium:size=14
bold-text-in-bright=palette-based

[scrollback]
indicator-position=none

[colors-dark]
foreground=b98000
background=000000
alpha=0.60

# URxvt.color4: cyan
regular4=00ffff

# URxvt.color12: #1f77dd
bright4=1f77dd
